jobs:
  - job: build_android_samples
    displayName: Build Android samples
    pool:
      vmImage: 'macos-latest'
    steps:
      - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
        displayName: 'Select the Xamarin SDK version'
        enabled: false
      - task: MSBuild@1
        displayName: Build Android samples
        inputs:
          solution: '**/*Droid*.csproj'
          configuration: 'Debug'
          msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: '16.0'