jobs:
- task: AndroidSigning@3
  inputs:
    apkFiles: 'outputs\apk*.apk'
    apksignerKeystoreFile: 'keystore.jks'
    apksignerKeystorePassword: 'lascha100'
    apksignerKeystoreAlias: 'key1'
    apksignerKeyPassword: 'lascha100'
  
- job: build_android_samples
  displayName: Build Android samples
  pool:
    vmImage: 'macos-latest'
  steps:
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
    displayName: 'Select the Xamarin SDK version'
    enabled: false


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: '16.0'
      - task: MSBuild@1
        displayName: Build Android samples
        inputs:
          solution: '**/*Droid*.csproj'
          configuration: 'Debug'
          msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'

- task: AndroidSigning@3
  inputs:
    apkFiles: outputs\apk*.apk 
    apksign: true # Optional
    apksignerKeystoreFile: keystore.jks # Required when apksign == True
    #apksignerKeystorePassword: # Optional
    #apksignerKeystoreAlias: # Optional
    #apksignerKeyPassword: # Optional
    #apksignerArguments: '--verbose' # Optional
    #apksignerFile: # Optional
    #zipalign: true # Optional
    #zipalignFile: # Optional